name: simceltest
channels:
  - conda-forge
  - defaults
dependencies:
  # Core scientific stack
  - python=3.10
  - numpy=2.0.1
  - pandas=2.2.2
  - matplotlib=3.9.2
  - scipy=1.13.1

  # Modeling
  - scikit-learn=1.4.2
  - xgboost=2.1.3
  - pyyaml=6.0.2
  - ipykernel=6.29.5

  # Testing
  - pytest=8.2.1
  - pytest-cov=5.0.0

  # Pip is included for any extras not on conda
  - pip
